const { DataTypes } = require("sequelize");

module.exports = (sequelize) => {
  return sequelize.define(
    "EchohuntSocialListeningPost",
    {
      id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true, comment: "帖子事实记录 ID" },
      boardId: { type: DataTypes.UUID, allowNull: false, comment: "关联 EchohuntSocialListeningBoards.id" },
      tweetId: { type: DataTypes.STRING(64), allowNull: false, comment: "X/Twitter tweet id；同一看板内唯一去重" },
      authorTwitterId: { type: DataTypes.STRING(64), allowNull: false, comment: "帖子作者 Twitter user id" },
      authorHandle: { type: DataTypes.STRING(128), allowNull: true, comment: "帖子作者 handle 快照" },
      authorName: { type: DataTypes.STRING(255), allowNull: true, comment: "帖子作者展示名快照" },
      authorAvatar: { type: DataTypes.TEXT, allowNull: true, comment: "帖子作者头像 URL 快照" },
      authorFollowersCount: { type: DataTypes.BIGINT, allowNull: true, comment: "帖子作者粉丝数快照" },
      authorGlobalRank: { type: DataTypes.INTEGER, allowNull: true, comment: "帖子作者全球 KOL 排名快照" },
      authorCnRank: { type: DataTypes.INTEGER, allowNull: true, comment: "帖子作者华语 KOL 排名快照" },
      authorIsCn: { type: DataTypes.BOOLEAN, allowNull: true, comment: "帖子作者是否华语账号快照，来自 dev.twitter_user.ai.is_cn" },
      postCreatedAt: { type: DataTypes.DATE, allowNull: false, comment: "帖子发布时间，来自 dev.tweet.create_time" },
      text: { type: DataTypes.TEXT, allowNull: true, comment: "帖子原文" },
      normalizedText: { type: DataTypes.TEXT, allowNull: true, comment: "归一化正文，用于关键词匹配和 AI 输入" },
      source: { type: DataTypes.STRING(32), allowNull: false, defaultValue: "mention", comment: "召回来源：mention/quote/reply/comment" },
      conversationId: { type: DataTypes.STRING(64), allowNull: true, comment: "会话根 tweet id" },
      quoteId: { type: DataTypes.STRING(64), allowNull: true, comment: "引用目标 tweet id" },
      replyId: { type: DataTypes.STRING(64), allowNull: true, comment: "回复目标 tweet id" },
      retweetId: { type: DataTypes.STRING(64), allowNull: true, comment: "转推原 tweet id；V1 默认不单独纳入但保留快照" },
      viewsCount: { type: DataTypes.BIGINT, allowNull: true, comment: "浏览量快照，来自 dev.tweet.statistic.views" },
      likesCount: { type: DataTypes.BIGINT, allowNull: true, comment: "点赞数快照，来自 dev.tweet.statistic.likes" },
      repostsCount: { type: DataTypes.BIGINT, allowNull: true, comment: "转推数快照，来自 dev.tweet.statistic.retweet_count" },
      quotesCount: { type: DataTypes.BIGINT, allowNull: true, comment: "引用数快照，来自 dev.tweet.statistic.quote_count" },
      repliesCount: { type: DataTypes.BIGINT, allowNull: true, comment: "回复数快照，来自 dev.tweet.statistic.reply_count" },
      sentiment: { type: DataTypes.STRING(32), allowNull: true, comment: "项目态度情绪：positive/neutral/negative/unknown" },
      projectAttitudeScore: { type: DataTypes.DECIMAL(8, 4), allowNull: true, comment: "项目态度 AI 分数，旧口径 score < 4 为负面" },
      sentimentScore: { type: DataTypes.DECIMAL(8, 4), allowNull: true, comment: "兼容情绪分数字段，默认等同 projectAttitudeScore" },
      sentimentSummaryZh: { type: DataTypes.TEXT, allowNull: true, comment: "项目态度中文摘要/原因" },
      topics: { type: DataTypes.JSONB, allowNull: true, comment: "主题标签 JSON，优先复用 dev.tweet.ai.domain_tag/crypto_sub_tags/ai_sub_tags" },
      keywords: { type: DataTypes.JSONB, allowNull: true, comment: "热词与命中关键词 JSON，用于词云和命中原因" },
      summaryZh: { type: DataTypes.TEXT, allowNull: true, comment: "中文摘要，优先复用 dev.tweet.ai.summary_cn" },
      summaryEn: { type: DataTypes.TEXT, allowNull: true, comment: "英文摘要，优先复用 dev.tweet.ai.summary_en" },
      titleZh: { type: DataTypes.TEXT, allowNull: true, comment: "中文标题，优先复用 dev.tweet.ai.title_cn" },
      titleEn: { type: DataTypes.TEXT, allowNull: true, comment: "英文标题，优先复用 dev.tweet.ai.title_en" },
      abstractZh: { type: DataTypes.TEXT, allowNull: true, comment: "中文长摘要，优先复用 dev.tweet.ai.abstract_cn" },
      abstractEn: { type: DataTypes.TEXT, allowNull: true, comment: "英文长摘要，优先复用 dev.tweet.ai.abstract_en" },
      tagStatus: { type: DataTypes.STRING(32), allowNull: true, comment: "标签处理状态：reused/generated/pending/failed/skipped" },
      summaryStatus: { type: DataTypes.STRING(32), allowNull: true, comment: "摘要处理状态：reused/generated/pending/failed/skipped" },
      attitudeStatus: { type: DataTypes.STRING(32), allowNull: true, comment: "项目态度处理状态：pending/succeeded/failed/skipped" },
      aiStatus: { type: DataTypes.STRING(32), allowNull: true, comment: "AI 总状态，汇总 tag/summary/attitude 状态" },
      aiAnalyzedAt: { type: DataTypes.DATE, allowNull: true, comment: "最近一次 AI 分析完成或尝试时间" },
      aiError: { type: DataTypes.TEXT, allowNull: true, comment: "AI 处理错误摘要，不保存 prompt 或敏感上下文" },
      aiSource: { type: DataTypes.STRING(64), allowNull: true, comment: "AI 字段来源：dev_tweet_ai/social_listening_generated/project_attitude/mixed" },
      rawTweet: { type: DataTypes.JSONB, allowNull: true, comment: "原始推文必要片段快照，避免前台实时扫 dev.tweet" },
      rawAuthor: { type: DataTypes.JSONB, allowNull: true, comment: "作者资料必要片段快照，避免前台实时扫 dev.twitter_user" },
    },
    {
      tableName: "EchohuntSocialListeningPosts",
      timestamps: true,
      indexes: [
        { name: "ux_echohunt_sl_posts_board_tweet", fields: ["boardId", "tweetId"], unique: true },
        { name: "idx_echohunt_sl_posts_board_created", fields: ["boardId", "postCreatedAt"] },
        { name: "idx_echohunt_sl_posts_board_sentiment_created", fields: ["boardId", "sentiment", "postCreatedAt"] },
        { name: "idx_echohunt_sl_posts_board_author", fields: ["boardId", "authorTwitterId"] },
        { name: "idx_echohunt_sl_posts_board_global_rank", fields: ["boardId", "authorGlobalRank"] },
      ],
    }
  );
};
