module.exports = [
  {
    nacosCampaignId: "bybit2",
    campaignKey: "bybit2",
    slug: "bybit2",
    displayNameZh: "Hunter Gala Season 6",
    displayNameEn: "Hunter Gala Season 6",
    webAnnouncementZh: "Bybit Hunter Gala Season 2强势回归！",
    webAnnouncementEn: "Bybit Hunter Gala Season 2 is back!",
    webRewardTextZh: "奖池：20,000 $USDC",
    webRewardTextEn: "Reward: 20,000 $USDC",
    logos: [
      { image: "/whitexhunt.png", label: "XHunt Logo" },
      { image: "/bybit.jpg", label: "Bybit Official Logo" },
    ],
    sortWeight: 600,
  },
  {
    nacosCampaignId: "realgo",
    campaignKey: "realgo",
    slug: "realgo",
    displayNameZh: "RealGo Leaderboard",
    displayNameEn: "RealGo Leaderboard",
    webAnnouncementZh: "我们很高兴推出 @RealGoOfficial 排行榜！Let’s RealGo！",
    webAnnouncementEn: "We're excited to launch the @RealGoOfficial Leaderboard! Let's RealGo!",
    webRewardTextZh: "奖池：10,000 USDT + 70,000 RT + 20 Genesis Mini Harvester",
    webRewardTextEn: "Reward: 10,000 USDT + 70,000 RT + 20 Genesis Mini Harvester",
    webNoteZh: "注：$RT 基于 1 亿美元 FDV 估值计算",
    webNoteEn: "Note: $RT based on $100M FDV",
    logos: [
      { image: "/whitexhunt.png", label: "XHunt Logo" },
      { image: "/realgologo.PNG", label: "RealGo Logo" },
    ],
    sortWeight: 590,
  },
  {
    nacosCampaignId: "mantle3",
    campaignKey: "mantle3",
    slug: "mantle3",
    displayNameZh: "Mantle Season 3",
    displayNameEn: "Mantle Season 3",
    webAnnouncementZh: "@0xMantleCN 再次与 @xhunt_ai 达成合作！",
    webAnnouncementEn: "@0xMantleCN is partnering with @xhunt_ai again!",
    webRewardTextZh: "奖池：10,000 $USDC",
    webRewardTextEn: "Reward: 10,000 $USDC",
    logos: [
      { image: "/whitexhunt.png", label: "XHunt Logo" },
      { image: "/MANTLE.png", label: "Mantle Logo" },
    ],
    sortWeight: 580,
  },
  {
    nacosCampaignId: "bybit",
    campaignKey: "bybit",
    slug: "bybit",
    displayNameZh: "Hunter Gala Season 3",
    displayNameEn: "Hunter Gala Season 3",
    webAnnouncementZh: "Bybit重磅登场！",
    webAnnouncementEn: "Hunter Gala Season 3 is back - and we've leveled up!",
    webRewardTextZh: "奖池：20,000 $USDC",
    webRewardTextEn: "Reward: 20,000 $USDC",
    logos: [
      { image: "/whitexhunt.png", label: "XHunt Logo" },
      { image: "/bybit.jpg", label: "Bybit Alpha Logo" },
    ],
    sortWeight: 400,
  },
  {
    nacosCampaignId: "mantle2",
    campaignKey: "mantle2",
    slug: "mantle2",
    displayNameZh: "Mantle Season 2",
    displayNameEn: "Mantle Season 2",
    webAnnouncementZh: "Mantle强势回归！",
    webAnnouncementEn: "Hunter Gala Season 2 is back - and we've leveled up!",
    webRewardTextZh: "奖池：20,000 $USDC",
    webRewardTextEn: "Reward: 20,000 $USDC",
    logos: [
      { image: "/whitexhunt.png", label: "XHunt Logo" },
      { image: "/MANTLE.png", label: "Mantle Logo" },
    ],
    sortWeight: 390,
  },
  {
    nacosCampaignId: "mantle",
    campaignKey: "mantle",
    slug: "mantle",
    displayNameZh: "Mantle Season 1",
    displayNameEn: "Mantle Season 1",
    webAnnouncementZh: "我们很兴奋地推出 Season 1 Hunter 排行榜！",
    webAnnouncementEn: "We are excited to launch the Season 1 of Hunter leaderboard!",
    webRewardTextZh: "奖池：30,000 $MNT",
    webRewardTextEn: "Reward: 30,000 $MNT",
    logos: [
      { image: "/whitexhunt.png", label: "XHunt Logo" },
      { image: "/MANTLE.png", label: "Mantle Logo" },
    ],
    sortWeight: 380,
  },
];
